name: repromockito
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  mockito: ^5.4.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
